import { Inter } from "next/font/google";
import "./globals.css";
import {
  TooltipProvider
} from "@/components/ui/tooltip"
import { NextAuthProviders, } from "./Providers";
import { DepartmentProvider } from '@/contexts/DepartmentContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProviders>
          <TooltipProvider>
            <DepartmentProvider>
              {children}
            </DepartmentProvider>
          </TooltipProvider>
        </NextAuthProviders>
      </body>
    </html>
  );
}
